name = "screenshot-pwa"
compatibility_date = "2024-01-15"
type = "webpack"
account_id = "" # You'll need to add your Cloudflare account ID here
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./build/web"
entry-point = "workers-site"

[build]
command = "sh build.sh"
output_dir = "build/web"
upload.format = "service-worker"
